version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=xnjnjgfcc22
      - POSTGRES_DB=ncu
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass htlbcgfcc21
    ports:
      - '6379:6379'
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  nest-api:
    container_name: nest-api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '7070:7070'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./server/.env
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '10000:3000'
    depends_on:
      - nest-api
    env_file:
      - ./client/.env
volumes:
  postgres:
    driver: local
  redis:
    driver: local
  nest-api:
    driver: local
  client:
    driver: local
networks:
  client:
    driver: 'bridge'
  nest-api:
    driver: 'bridge'
  postgres:
    driver: 'local'
  redis:
    driver: 'local'
