version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=xnjnjgfcc22
      - POSTGRES_DB=ncu
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
  redis:
