version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=xnjnjgfcc22
      - POSTGRES_DB=ncu
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass htlbcgfcc21
    ports:
      - '6379:6379'
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  # nest-api:
  #   container_name: nest-api
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - 7070:7070
  #   depends_on:
  #     - postgres
  #     - redis
  #   env_file:
  #     - ./server/docker.env
volumes:
  postgres:
    driver: local
  redis:
    driver: local
  # nest:
  #   driver: local
